# spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/security
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: 
#    password: 
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQLDialect

  # security:
  #   user:
  #     name: 
  #     password: 
