name: Docker CI/CD

on:
  push:
    branches:
      - master  # master 브랜치에 push 시 자동 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # JDK 설정 및 Gradle 빌드
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build

      # Docker 로그인 (Docker Hub 사용자명과 비밀번호가 GitHub Secrets에 저장돼 있어야 함)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker 이미지 빌드
      - name: Build Docker image
        run: docker build -t nigoleto/myapp:latest .

      # Docker Hub에 이미지 푸시
      - name: Push Docker image
        run: docker push nigoleto/myapp:latest
