name: CI Workflow  # 워크플로우 이름

on:
  push:
    branches:
      - main  # main 브랜치에 코드 푸시될 때 실행

jobs:
  build:  # 'build'라는 이름의 작업 정의
    runs-on: ubuntu-latest  # 작업을 실행할 환경 지정

    steps:  # 작업에서 실행할 단계들
      - name: Checkout code  # 코드 체크아웃 단계
        uses: actions/checkout@v2  # GitHub에서 제공하는 액션을 사용하여 코드 가져오기

      - name: Run a one-line script  # 간단한 명령어 실행 예시
        run: echo "Hello, GitHub Actions!"  # 스크립트 실행
